spring:
  profiles:
    active: dev

---
spring:
  application:
    ### 当前服务名字
    name: eureka-peer
  profiles: dev
server:
  port: 10000

---
spring:
  application:
    name: eureka-peer2
  profiles: dev1
server:
  port: 10001

---
spring:
  application:
    name: eureka-peer3
  profiles: dev2
server:
  port: 10002

---
eureka:
  instance:
    hostname: dev1
## eureka client
  client:
    ##检索服务
    fetch-registry: false
    ##是否将自己服务注册到eureka
    register-with-eureka: false
    ##客户端默认区这个地方找注册中心
    service-url:
      defaultZone: http://localhost:10000/eureka/
## eureka server
  server:
    ### 当eureka启动时，不能从集群节点中获取到instance注册信息，应该等多久
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    ### eureka 多长时间更新一次数据
    peer-eureka-nodes-update-interval-ms: 100000